c_compiler:            # [win]
  - clang              # [win]
cxx_compiler:          # [win]
  - clang              # [win]
c_compiler_version:    # [win]
  - '20'               # [win]
cxx_compiler_version:  # [win]
  - '20'               # [win]

numpy:
  # python 3.10
  - 2.4.4
  # python 3.11
  - 2.4.4
  # python 3.12
  - 2.4.4
  # python 3.13
  - 2.4.4
  # python 3.14
  - 2.4.4

blas_impl:
  - mkl                        # [(x86 or x86_64) and not osx]
  - openblas

fortran_compiler:
  - flang             # [win]
fortran_compiler_version:
  - 20                # [win]