{% set version = "3.0.0" %}

package:
  name: scs
  version: {{ version }}

source:
  - url: https://github.com/bodono/scs-python/archive/refs/tags/{{ version }}.tar.gz
    sha256: b962c8d757f49602aa2223f88b303504fe6dbf8249f2378e323ca197ed030202
  # include submodule (not in github tarball due to dear-github/dear-github#214)
  - git_url: https://github.com/cvxgrp/scs.git
    git_rev: 5be0e1684d12c4cfd4d22c5fba236a84a092ab5b
    folder: scs

build:
  number: 1
  script:
    - export BLAS_LAPACK_LIB_PATHS="$PREFIX/lib"    # [unix]
    - export BLAS_LAPACK_LIBS="lapack:cblas:blas"   # [unix]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - libblas
    - liblapack
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.2
  run_constrained:
    # avoid installing incompatible cvxpy
    - cvxpy >1.1.15

test:
  imports:
    - scs
    - _scs_direct
    - _scs_indirect
  requires:
    - pytest
  source_files:
    - test/
  commands:
    - pytest test/ -v

about:
  home: https://github.com/bodono/scs-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface for SCS, which solves convex cone problems
  description: |
    Solves convex cone programs via operator splitting.
    Can solve: linear programs (LPs), second-order cone programs (SOCPs),
    semidefinite programs (SDPs), exponential cone programs (ECPs),
    and power cone programs (PCPs), or problems with any combination of
    those cones.
  dev_url: https://github.com/bodono/scs-python

extra:
  recipe-maintainers:
    - djsutherland
    - mcg1969
    - h-vetinari
