{% set version = "2.1.4" %}

package:
  name: scs
  version: {{ version|replace('-', '.') }}    # 2.1.1-2 => 2.1.1.2

source:
  url: https://pypi.io/packages/source/s/scs/scs-{{ version }}.tar.gz
  sha256: ddd6614db7f0e63b69672cfd02ba2c8423dade33a58b0a341a5119091c501739

build:
  number: 0
  script:
    - export BLAS_LAPACK_LIB_PATHS="$PREFIX/lib"    # [unix]
    - export BLAS_LAPACK_LIBS="lapack:cblas:blas"   # [unix]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - libblas
    - liblapack
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.2

test:
  imports:
    - scs
    - _scs_direct
    - _scs_indirect
  requires:
    - nose
  source_files:
    - test/
  commands:
    - nosetests test

about:
  home: https://github.com/bodono/scs-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface for SCS, which solves convex cone problems
  description: |
    Solves convex cone programs via operator splitting.
    Can solve: linear programs (LPs), second-order cone programs (SOCPs),
    semidefinite programs (SDPs), exponential cone programs (ECPs),
    and power cone programs (PCPs), or problems with any combination of
    those cones.
  dev_url: https://github.com/bodono/scs-python

extra:
  recipe-maintainers:
    - djsutherland
    - mcg1969
    - h-vetinari
