{% set name = "scs" %}
{% set version = "2.1.0" %}
{% set sha256 = "1d67a34b36ef31fc23eeb29c97d3b126d8c70f6420e4da600d674f478d1985d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed --verbose .
  skip: true  # figure out Windows build later....  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - numpy
    - openblas  # links to the blas picked up from numpy version
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - openblas
    - scipy >=0.13.2

test:
  imports:
    - scs
    - _scs_direct
    - _scs_indirect
  requires:
    - nose
  source_files:
    - test/
  commands:
    - nosetests test

about:
  home: https://github.com/bodono/scs-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python interface for SCS, which solves convex cone problems'
  description: |
    Solves convex cone programs via operator splitting.
    Can solve: linear programs (LPs), second-order cone programs (SOCPs),
    semidefinite programs (SDPs), exponential cone programs (ECPs),
    and power cone programs (PCPs), or problems with any combination of
    those cones.
  doc_url: https://github.com/bodono/scs-python
  dev_url: https://github.com/bodono/scs-python

extra:
  recipe-maintainers:
    - dougalsutherland
