{% set version = "3.2.3" %}
{% set name = "scs" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3bd779e7e977e3ae5a2f2035aa4c2a309e29082d59a722d5d6592edc4bdb4b3

build:
  skip: true  # [py<37]
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv  # [unix]
    - {{ PYTHON }} -m setup.py install --scs --mkl -vv  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libopenblas 0.3.21  # [unix]
    - mkl  # [win]
    - python
    - setuptools <65.6.0
    - wheel
    - pip
    - numpy
  run:
    - python
    - mkl  # [x86]
    - libopenblas  # [not win]
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.2
  run_constrained:
    # avoid installing incompatible cvxpy
    - cvxpy >1.1.15

test:
  imports:
    - scs
    - _scs_direct
    - _scs_indirect
  requires:
    - pytest
    - pip
  source_files:
    - test/
  commands:
    - pytest test/ -v
    - pip check

about:
  home: https://github.com/bodono/scs-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface for SCS, which solves convex cone problems
  description: |
    Solves convex cone programs via operator splitting.
    Can solve: linear programs (LPs), second-order cone programs (SOCPs),
    semidefinite programs (SDPs), exponential cone programs (ECPs),
    and power cone programs (PCPs), or problems with any combination of
    those cones.
  dev_url: https://github.com/bodono/scs-python
  doc_url: https://www.cvxgrp.org/scs/

extra:
  recipe-maintainers:
    - djsutherland
    - mcg1969
    - h-vetinari
