{% set name = "scs" %}
{% set version = "3.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 388ba6e6d77ac3ded38eb782eafece3df7b56ace2929135760a4bd7b251b6a08

build:
  number: 0
  # Windows is missing lapack and blas. 
  # Substituting mkl isn't supported by the python wrapper.
  skip: true  # [py<39 or win]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - meson-python
    - ninja-base
    - openblas {{ openblas }}
    - numpy {{ numpy }}
    - scipy
  run:
    - python
    - openblas
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.2
  run_constrained:
    # avoid installing incompatible cvxpy
    - cvxpy >1.1.15

test:
  source_files:
    - test
  imports:
    - scs
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v test

about:
  home: https://github.com/bodono/scs-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface for SCS, which solves convex cone problems
  description: |
    Solves convex cone programs via operator splitting.
    Can solve: linear programs (LPs), second-order cone programs (SOCPs),
    semidefinite programs (SDPs), exponential cone programs (ECPs),
    and power cone programs (PCPs), or problems with any combination of
    those cones.
  dev_url: https://github.com/bodono/scs-python
  doc_url: https://www.cvxgrp.org/scs/

extra:
  recipe-maintainers:
    - djsutherland
    - mcg1969
    - h-vetinari
