travis:
  secure:
    BINSTAR_TOKEN: CRBREmRipHNToVa8eOa31xBYdZUQNJwnY4k6pV1RdxeGIXJHdtgceamFZlZlVdhDmIXWXXm2nhHrEkky2qLNBiyP+TOwvOgrOpxMB2IjyH9pCS7eA7al2EhAzN/zXa7UgPDtVvFp44CFQWs44bi0S4F7uKPc5unmFtdNPIGjHKSUhUjQoM8xpH8V6dp6EhgQBY9oXNj6j563piRvcASS8FwSxtabxsQRhtV8VxIyDWTbQzUWWQMWotzMwUFKuXdt1MTfy5RVZHOdpoQAmA5vneZHx52vXZK7iFsXPOEWb91/88nDDhxq88Y5ELm05OIgipZwET/nMMjTEq+/D6SgNexkptfvpcAT4PPkMIK8EUN/1LtUvpCinH+VzrCHN7J9of8MDtw89siYOl2P6MDNBEhsEf65bzmsWtuvVBRy3D7VWXgc16Qw0D4GuopcBukBkHqmcObQFa58rAVDp7/L+MBAS54BzMPLS3EqbIHFRZSBzN5J3qnLCg4qdfwvslsoxbvfSzt6DGENk9P2Hm0vEnHMa0Gbuqa2jrZampHbnOpC8gOi3YYwbY7Q+Jmsy5MJAKIAuzD6F8BMRgHRQWJvq48MHoDEsEvA5H1NYuRKw1CGLV77ur/XB56/4Rt4cdPxj5BcbWvwty2tCjNWeKnSOeH5gretxO6NIsxFL27BHus=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
